include:
  - project: 'cloudybay/cb_dood'
    ref: ci-test
    file: '/templates/.gitlab-ci.yml'
  - project: 'cloudybay/cb_dood'
    ref: ci-test
    file: '/templates/.gitlab-ci-backend.yml'

variables:
  FRONTEND_PROJECT: cloudybay%2F{ PROJECT_NAME }-frontend
  IMAGE_PROJECT_DIR: /opt/CloudyBay/{ PROJECT_NAME }
  STAGING_SERVER_PORT: { STAGING_SERVER_PORT }

build:
  extends: .build

test:
  extends: .test

scanner:
  extends: .scanner

staging:
  extends: .staging

production:
  extends: .production
