include:
  - project: 'cloudybay/cb_dood'
    ref: master
    file: '/templates/.gitlab-ci.yml'
  # 如果有前端的話 需要特別的 ci script 去 pull 前端的 artifacts
  # - project: 'cloudybay/cb_dood'
  #   ref: master
  #   file: '/templates/.gitlab-ci-backend.yml'

variables:

  # Must be set...
  # 如果有前端的話
  # FRONTEND_PROJECT: cloudybay%2Fhouse_frontend
  IMAGE_PROJECT_DIR: /opt/CloudyBay/{project}
  STAGING_SERVER_PORT: {port}

deploy_production:
  environment:
    url: ''
