include:
  - project: 'cloudybay/cb_dood'
    ref: ci-test-v2
    file: '/templates/.gitlab-ci.yml'
  - project: 'cloudybay/cb_dood'
    ref: ci-test-v2
    file: '/templates/.gitlab-ci-backend.yml'

variables:
  FRONTEND_PROJECT: cloudybay%2F{{ project_name }}_frontend
  IMAGE_PROJECT_DIR: /opt/CloudyBay/{{ project_name }}
  HOST_PROJECT_DIR: /opt/CloudyBay/{{ project_name }}

build:
  extends: .build

test:
  extends: .test

scanner:
  extends: .scanner

staging:
  extends: .staging

production:
  extends: .production
