version: '3.7'

services:
  web:
    image: nginx
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./app-data:${IMAGE_PROJECT_DIR}
      - ./app-data/conf/${OPERATION_MODE}/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: ${IMAGE_PROJECT_DIR}
    env_file:
      - ./.env

  app:
    image: "${DOCKER_IMAGE}"
    restart: unless-stopped
    init: true
    stdin_open: true
    tty: true
    expose:
      - 8080
    volumes:
      - ./app-data:${IMAGE_PROJECT_DIR}
    entrypoint: ./entrypoint.sh
    command: cloudybay 1000
    env_file:
      - ./.env
