version: '3.7'

services:
  init:
    image: $CONTAINER_IMAGE
    command: ./init.sh
    env_file:
      - ./.env

  app.staging:
    image: $CONTAINER_IMAGE
    restart: unless-stopped
    init: true
    expose:
      - 8000
    volumes:
      - ./logfiles:/var/log/app
      - ./data:/data
    entrypoint: ./entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - staging

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.4.2
    restart: unless-stopped
    hostname: {{ repository_name }}_beat
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logfiles:/var/log/app:ro
      - filebeat:/usr/share/filebeat/data

volumes:
  filebeat:

networks:
  staging:
    name: traefik_net
    external: true
