version: '3.7'

services:
  init:
    image: $BACKEND_IMAGE
    command: ./init.sh
    profiles:
      - prod
      - staging
    env_file:
      - ./.env

  web.prod:
    image: $FRONTEND_IMAGE
    restart: unless-stopped
    profiles:
      - prod
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./logfiles:/var/log/web

  web.staging:
    image: $FRONTEND_IMAGE
    restart: unless-stopped
    profiles:
      - staging
    expose:
      - 80
    hostname: {{ project_name }}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ project_name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ project_name }}.rule=Host(`{{ project_name }}-staging.cloudybay.com.tw`)"
      - "traefik.http.routers.{{ project_name }}.tls=true"
    volumes:
      - ./logfiles:/var/log/web
    networks:
      - internal
      - staging

  app.prod:
    image: $BACKEND_IMAGE
    restart: unless-stopped
    hostname: app
    init: true
    profiles:
      - prod
    expose:
      - 8080
    volumes:
      - ./logfiles:/var/log/app
    entrypoint: ./entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - internal

  app.staging:
    image: $BACKEND_IMAGE
    restart: unless-stopped
    hostname: app
    init: true
    profiles:
      - staging
    expose:
      - 8080
    volumes:
      - ./logfiles:/var/log/app
    entrypoint: ./entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - internal

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.4.2
    restart: unless-stopped
    hostname: {{ repository_name }}_beat
    profiles:
      - staging
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logfiles:/var/log/app:ro
      - filebeat:/usr/share/filebeat/data

volumes:
  filebeat:

networks:
  staging:
    external:
      name: traefik_net
  internal:
