services:
  web:
    hostname: {{ project_name }}
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ project_name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ project_name }}.rule=Host(`{{ project_name }}.dev.cloudybay.com.tw`)"
      - "traefik.http.routers.{{ project_name }}.tls=true"
    networks:
      - internel
      - default

  app:
    networks:
      - internel

networks:
  default:
    external:
      name: traefik_net
  internel:
