version: '3.7'

services:
  web:
    image: nginx
    ports:
      - "${STAGING_SERVER_PORT}:80"
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - .:${IMAGE_PROJECT_DIR}
    working_dir: ${IMAGE_PROJECT_DIR}
    entrypoint: ./start-web.sh
    env_file:
      - ./.env

  app:
    image: "${DOCKER_IMAGE}"
    restart: unless-stopped
    stdin_open: true
    tty: true
    expose:
      - 8080
    volumes:
      - .:${IMAGE_PROJECT_DIR}
    env_file:
      - ./.env
