ARG CONTAINER_IMAGE

FROM ${CONTAINER_IMAGE} as app

FROM nginx:alpine-slim

COPY --from=app /app/static /app/static

COPY --from=app /app/www /app/www

COPY --from=app /app/conf/nginx.conf /etc/nginx/conf.d/default.conf
