---

- name: Update app images
  hosts: staging
  vars:
    image: { registry: 'registry.gitlab.com', name: 'cloudybay/{{ repository_name }}', tag: "{% verbatim %}{{ version }}{% endverbatim %}" }

{% verbatim %}
  tasks:
    - name: Login to Gitlab Docker registry
      become: true
      community.docker.docker_login:
        username: {}
        password: {}
        registry_url: registry.gitlab.com

    - name: Pull images
      become: true
      community.docker.docker_image:
        name: "{{ image.registry }}/{{ image.name }}"
        tag: "{{ image.tag }}"
        source: pull
        force_source: true
      tags:
        - pull

    - name: Make sure destination dir exists
      ansible.builtin.file:
        path: "{{ host_project_dir }}/logfiles"
        state: directory

    - name: Get SECRET_KEY
      ansible.builtin.shell: "openssl rand -base64 40"
      register: seret_key
      tags:
        - get_secret_key

    - name: Creating env file with content
      copy:
        dest: "{{ host_project_dir }}/.env"
        content: |
          OPERATION_MODE={{ deploy_env }}
          SECRET_KEY={{ seret_key.stdout }}
          DATABASES_DEFAULT_PASSWORD={{ DATABASES_DEFAULT_PASSWORD }}
          BASE_DIR=/app
      vars:
        DATABASES_DEFAULT_PASSWORD: {}

      tags:
        - create_env

    - name: Copy docker-compose.yml
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: "{{ host_project_dir }}/docker-compose.yml"
      vars:
        CONTAINER_IMAGE: "{{ image.registry }}/{{ image.name }}:{{ image.tag }}"
      tags:
        - copy_docker-compose

    - name: Copy filebeat.docker.yml
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../filebeat.docker.yml"
        dest: "{{ host_project_dir }}/filebeat.docker.yml"
        mode: u=rw,g=r,o=r
      tags:
        - copy_filebeat.docker

    - name: docker-compose down
      become: true
      ansible.builtin.shell: docker-compose down
      args:
        chdir: "{{ host_project_dir }}/"
      tags:
        - docker-compose-down

    - name: docker-compose up
      become: true
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: "{{ host_project_dir }}/"
      tags:
        - docker-compose-up-d

    - name: Remove old images
      become: true
      ansible.builtin.shell: docker rmi -f $(docker images -f dangling=true -q) || true

{% endverbatim %}